environment:
  TOKEN: ${TOKEN}
packages:
  - name: app
    shared: false
    parameters: {}
    annotations: {}
    functions:
      - name: redeploy
        binary: false
        main: ""
        runtime: nodejs:default
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
